version: 2.1

orbs:
  scala-build: liveintent/scala-build@13.1

parameters:
  ssh_key_fingerprint:
    type: string
    default: "d7:1a:f0:af:4a:ec:2f:04:c3:8d:d2:4f:7b:f7:1c:53"
  cache_prefix:
    type: string
    default: v1
  jdk_version:
    type: string
    default: "21"

references:
  tagged_release: &tagged_release
    tags:
      only: /^.+$/
    branches:
      ignore: /.*/

  untagged_snapshot: &untagged_snapshot
    tags:
      only: /^$/
    branches:
      ignore: /update\/.*/

  update_pr: &update_pr
    branches:
      only: /update\/.*/

workflows:
  version: 2
  build_and_publish:
    jobs:
      - scala-build/compile:
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          name: compile
          context:
            - org-global
            - artifactory
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          filters:
            tags:
              only: /.*/

      - scala-build/lint:
          name: check
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          filters:
            tags:
              only: /.*/
          requires:
            - compile

      - scala-build/test:
          name: test
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          use_docker_compose: true
          docker_compose_file: docker-compose.yml
          docker_compose_ports: "4566"
          requires:
            - compile
          filters:
            tags:
              only: /.*/

      - scala-build/publish_sbt:
          name: publish_snapshot
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          requires:
            - check
            - test
          filters:
            <<: *untagged_snapshot

      - scala-build/merge_pr:
          context: org-global
          requires:
            - check
            - test
          filters:
            <<: *update_pr

      - release?:
          type: approval
          requires:
            - check
            - test
          filters:
            <<: *untagged_snapshot
            branches:
              only: master

      - scala-build/release:
          name: release
          context: [org-global, artifactory]
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          ssh_key_fingerprint: << pipeline.parameters.ssh_key_fingerprint >>
          requires:
            - release?
          filters:
            <<: *untagged_snapshot
            branches:
              only: master

      - scala-build/publish_sbt:
          name: publish_tagged_release
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          requires:
            - check
            - test
          filters:
            <<: *tagged_release

      - scala-build/trigger_liveintent_steward:
          context: org-global
          requires:
            - publish_tagged_release
          filters:
            <<: *tagged_release
