addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"   % "0.14.10")
addSbtPlugin("com.github.sbt"            % "sbt-protobuf"   % "0.7.1")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.9")